#!/bin/sh
#
# @name Noctua Plane SITL
# https://docs.px4.io/main/en/advanced_config/parameter_reference.html

. ${R}etc/init.d/rc.fw_defaults



param set-default FW_LND_ANG 8

param set-default NPFG_PERIOD 12

param set-default FW_MAN_P_MAX 30

param set-default FW_PSP_OFF 2		#pitch at level flight !!!
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15


param set-default FW_THR_MIN 0.05	#minimum throttle
param set-default FW_THR_TRIM 0.3	#throttle at level flight !!!

param set-default FW_T_CLMB_MAX 8	#max climb rate
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

param set-default FW_W_EN 0

param set-default MIS_TAKEOFF_ALT 30

param set-default NAV_ACC_RAD 15
param set-default NAV_DLL_ACT 2		#return if lost

param set-default RWTO_TKOFF 1

param set-default CA_AIRFRAME 1

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 1.5	#propeller position !!!

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS3_TRQ_Y 1.0
param set-default CA_SV_CS3_TYPE 4

param set-default PWM_MAIN_FUNC3 204
param set-default PWM_MAIN_FUNC4 205

param set-default PWM_MAIN_FUNC5 101	#throttle

param set-default PWM_MAIN_FUNC6 201
param set-default PWM_MAIN_FUNC7 202
param set-default PWM_MAIN_FUNC8 203
param set-default PWM_MAIN_FUNC9 206
param set-default PWM_MAIN_REV 256
